name: Your New Jekyll Site
markdown: rdiscount
rdiscount:
    extensions: [smart]
pygments: true
exclude: 
  - Gemfile
  - Gemfile.lock
  - tasks
  - README.md
  - node_modules
  - Gruntfile.js
  - package.json
  - sftp-config.json
